version: '3.5'

services:
    sdn-redis:
        container_name: sdn-redis
        image: redis:7.0.4
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./data/cache:/data
        networks:
            docker:
                ipv4_address: 172.19.1.3
    
    sdn-flask:
        container_name: sdn-flask
        build: ./docker-images/flask
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/opt/app/
        networks:
            docker:
                ipv4_address: 172.19.1.2
        depends_on:
            - sdn-redis

    sdn-webui:
        image: webui:latest
        volumes:
            - ../webui:/webui/
        ports:
            - "5000:5000"

networks:
    docker:
        ipam:
            config:
                - subnet: 172.19.1.0/24
