apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 7001
    protocol: TCP
    nodePort: 7001
    targetPort: 7001
    name: webui
  - port: 8081
    protocol: TCP
    nodePort: 8081
    targetPort: 8081
    name: combat
  - port: 9001
    protocol: TCP
    nodePort: 9001
    targetPort: 9001
    name: text
  selector:
    app: nginx