apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos
  template:
    metadata:
      labels:
        app: onos
    spec:
      containers:
      - name: onos
        image: jakeyang0924/onos:test
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
        - containerPort: 6653
