apiVersion: apps/v1
kind: Deployment
metadata:
  name: text
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text
  template:
    metadata:
      labels:
        app: text
    spec:
      containers:
      - name: text
        image: jakeyang0924/text:test
        imagePullPolicy: Always
        ports:
        - containerPort: 9000