apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: video
        image: jakeyang0924/video:test
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8888