apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  # type: NodePort
  ports:
  - port: 7000
    protocol: TCP
    # nodePort: 7000
    targetPort: 7000
    name: webui
  selector:
    app: webui